### ISSUE TITLE
请问单模态与双模态的数据集处理和三模态的数据集处理一样吗？

### ISSUE THREAD

**Issue by asd123pwj** [ttaalle/multi-modal-vehicle-Re-ID#1]
您好，请问论文中 Table 3 中的 RGB/NIR/TIR/RGB-N/RGB-T 的数据集处理与 rgbir 文件夹里 RGB-N-T 三模态图片对应的数据集处理一样吗？
以及 RGB-N-T 是只使用了您论文中提出的三模态合并后的图片来训练及测试吗？有诸如 RGB query 到 NIR gallery 的处理吗？

**Comment by ttaalle** [comment]
是一样的，所有的图片都是配好了的，就是刚开始处理的时候一个裁成两份，一个裁成三份。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月5日(周六) 晚上7:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [ttaalle/multi-modal-vehicle-Re-ID] 请问单模态与双模态的数据集处理和三模态的数据集处理一样吗？ (Issue #1)




 
Closed #1.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
